version: '3.4'

services:
  redis:
    image: redis

  app:
    depends_on:
      - redis
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s 3000 -b '0.0.0.0'"  
    environment:
      - REDIS_URL=redis://redis:6379/0
    
volumes:
  redis:
  postgres: